### ISSUE TITLE
deep-equal crashes on newer React?

### ISSUE THREAD

**Issue by wmertens** [nfl/react-helmet#441] opened 2019-02-25 06:28 UTC
I've experienced some call-too-deep errors, and I think somehow React is introducing circular references and then deep-equal follows them.

I worked around this like so:

```js
import {isEqual} from 'lodash'

// Helmet uses deep-equal and sometimes crashes on circular objects
Helmet.prototype.shouldComponentUpdate = function(nextProps) {
	return !isEqual(this.props, nextProps)
}
```

It seems to work - lodash has circular reference protection.

**Comment by Bacto** [comment] 2019-02-25 15:41
I got the same error on Firefox (InternalError: too much recursion) with React 16.8.3 and Helmet 5.2.0.

Thanks for your code @wmertens, I'll test it :)

**Comment by enapupe** [comment] 2019-02-25 22:46
Ugh.. just spent 2+ hours on top of this.
They seem to have replaced `deep-equal` with `react-fast-compare` on sCU, which should fix it. But no version was published under v5 since a LONG time ago.

If any maintainer could check the possibility of publishing a minor/patch on top of that commit https://github.com/nfl/react-helmet/commit/1803f678b9d38b5ae91961ea13ea1c7fa7c9afe8

**Comment by tmbtech** [comment] 2019-02-26 01:21
Have you tried to use v.6-beta? 
More info here - https://github.com/nfl/react-helmet/pull/421#issuecomment-450449810

**Comment by enapupe** [comment] 2019-02-26 12:28
Yesterday I quickly tried it but didn't notice the import API change so most of my tests failed, I was too annoyed to debug that.

Now after reading that PR you linked it was pretty straightforward, already in prod.
Many thanks

**Comment by enapupe** [comment] 2019-02-26 12:30
I have to say though, it would be nice to keep v5 working, specially if it's a simple fix (publish that commit). Thanks again.

**Comment by tmbtech** [comment] 2019-02-28 23:19
I'm no longer working at the NFL. Someone on the NFL frontend team would need to do it.

**Comment by tedlin182** [comment] 2019-03-04 04:42
Yeah we ran into the same `maximum call stack` error issue with the latest CRA prod build. We ended up just removing `react-helmet` for now unfortunately. Upgrading to 6.0.0-beta didn't fix the issue for us.

**Comment by Maxwell2022** [comment] 2019-03-04 07:32
This fix is in master but not in `5.0.2`. [It has been fixed](1803f678b9d38b5ae91961ea13ea1c7fa7c9afe8) in November last year but there is still no release of the `5.x`. 
Until this gets released, I've published my own package for now `rl-react-helmet` which is just `5.0.2` + this patch.

**Comment by mbifulco** [comment] 2019-03-07 02:59
@cwelch5 - any chance you can give this issue some love? It looks like a quick release of this package to NPM would help lots of us out 🙏

**Comment by janhartmann** [comment] 2019-03-12 10:28
Finally I've found this issue!
I been spending 4 hours now debugging and now I've finally found the root cause. I would really appreciate an update to this. Thank you!

**Comment by mbifulco** [comment] 2019-03-12 11:41
@janhartmann it's a somewhat unsatisfying solution, but we got around this (for the time being) by using `react-helmet@6.0.0-beta` in our `package.json`.

**Comment by wmertens** [comment] 2019-03-12 11:49
I don't normally do this, but in this case of a seemingly abandoned library
I'd like to point out that the fork react-helmet-async is only a small
change to implement, it has the fix, it is updated, and it is better for
SSR.

Thanks to the NFL in any case for the great library!

**Comment by janhartmann** [comment] 2019-03-12 11:50
Cheers, thanks for the alternatives. I'll check it out!

**Comment by BicanMarianValeriu** [comment] 2019-03-18 10:36
Use props syntax instead of children html. It happened to me also when dispatching multiple redux actions (middlewares) on the same event (was trying to dispatch a set spinner action when fetching some data).

**Comment by FissionCat** [comment] 2019-04-30 10:40
@tmbtech I can see the fix has now been pushed to a branch - great! Is 5.2.1 going to be published to npm soon?

**Comment by kkoomen** [comment] 2019-04-30 15:24
I could really use this fix , so I hope this fix can be published quickly! 👍

**Comment by tmbtech** [comment] 2019-04-30 22:14
Sorry I don't have publishing right. @miblanchard @cwelch5 do you have any time to publish to NPM?

**Comment by tmbtech** [comment] 2019-05-01 00:52
@miblanchard was so kind and published an updated version. 

Closing, thank you all.

**Closed by tmbtech** 2019-05-01 00:52 UTC

**Comment by mbifulco** [comment] 2019-05-01 01:05
Oh my goodness, thank you so much @tmbtech and @miblanchard!

**Comment by kkoomen** [comment] 2019-05-01 07:07
@tmbtech @miblanchard Thanks!

**Comment by nandorojo** [comment] 2020-05-17 19:10
I still get errors with `6.0.0`, but the original [solution](https://github.com/nfl/react-helmet/issues/441) works for me.

**Comment by premvenud** [comment] 2020-09-24 17:43
I am facing the issue even after using v5.2.1, but the above give workaround works.
