### ISSUE TITLE
3.2 bug 

### ISSUE THREAD

**Issue by dlebedynskyi** [nfl/react-helmet#196] opened 2016-11-07 16:09 UTC
after update to ^3.2
```
Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. Check the render method of `App`.
```
on client side with 
![image](https://cloud.githubusercontent.com/assets/1182917/20064802/f2c10c10-a4d9-11e6-8388-c86848c5ffdc.png)

**Comment by cwelch5** [comment] 2016-11-07 16:30
Thanks.  Duplicate of #190 We will resolve quickly.

**Closed by cwelch5** 2016-11-07 16:30 UTC
Labels: duplicate
