### ISSUE TITLE
Feature request: inline <script type="javascript>...</script>

### ISSUE THREAD

**Issue by mfowlewebs** [nfl/react-helmet#389] opened 2018-07-19 20:54 UTC
We're attempting to load some script tags with text content, but we get a `TypeError: tag[primaryAttributeKey].toLowerCase is not a function` error when we try to create a `<script type="text/javascript" key="mykey">2+2</script>`.

From the [Reference Guide](https://github.com/nfl/react-helmet#reference-guide) I saw an example of a script of type `application/json+ld` and figured `text/javascript` would be fine, and help us avoid some ugly DOM manipulation code & eval() usage that we do now. The React-Helmet implementation may have to do this (to get scripts to evaluate) but at least it would be in a well-managed place.

Thanks for the cool library!! This made our code so much cleaner. Just, unbelievably so much less old-worldy DOM stuff going on. Nice. Thanks.

**Comment by Asday** [comment] 2018-08-11 13:05
I'd be interested to see a more real-world case than the one you provided.  So far I've yet to come across the need to dynamically inject javascript from within React.

**Comment by spiderpug** [comment] 2018-08-15 10:25
We provide a CMS to customer and they have the option to specify source code that should be added to the `<head>` of a page. In most cases they add third party vendor scripts (A/B testing, tracking, etc) that we have no control of in our app.

**Comment by Asday** [comment] 2018-08-15 12:32
My condolences.  I always hated working on CMSs.  :)

That said, I'm not able to reproduce your problem.  Would you be able to throw together a minimal repository for me to troubleshoot on?

**Comment by AubreyHewes** [comment] 2018-09-21 23:02
Is this not covered in the docs ?

e.g. something like

````javascript
<Head>
{
  headScripts.map((content) => (
    <script>{`${content}`}</script>
  ));
}
</Head>
````

**Comment by tmbtech** [comment] 2018-11-07 18:57
Closing, feel free to open a new issue if this hasn't been resolved.

**Closed by tmbtech** 2018-11-07 18:57 UTC
Labels: question

**Comment by Way-U-Need** [comment] 2019-03-18 12:39
how to solve 
TypeError: tag[primaryAttributeKey].toLowerCase is not a function in react helmet

**Comment by luxurystorecc1** [comment] 2026-05-19 00:35
Cheap NFL Jerseys USA: Licensed Gear, Custom Names, and Fan Shopping Intent

Cheap NFL jerseys in the United States continue to attract strong search demand because buyers want affordable fanwear that still feels trustworthy. A good article should start with licensed retail and explain how users move from a broad search to a more specific product page. That structure makes the content easier to read and more useful. [official NFL shop](https://www.nflshop.com/) [NFL Shop official online store](https://www.nflshopofficialonline-store.com/)

Many shoppers begin with a general keyword and then narrow down to a team, style, or collection. That is why cheap NFL jerseys online and an NFL jerseys collection page work so well together in one article. This mirrors real shopping behavior and makes the content feel natural. [cheap NFL jerseys online](https://www.cheapnfl-jerseys.com/) [NFL jerseys collection](https://www.nflshop.com/jerseys/d-2337111224+z-906686-2704878006)

Customization is a major buying trigger. A custom NFL jersey with name is often used for gifts, special events, or personal fan identity, so it should be presented as a normal option in the category. That makes the article more helpful and more practical. [custom NFL jersey with name](https://www.nflshopofficialonline-store.com/collections/custom-nfl-jersey) [custom football jerseys online](https://www.spized.com/us-en/custom-football-jerseys)

Accessories should be included because jersey shoppers often buy a complete look. Headwear, caps, and fan hats are common add-ons that help the article reflect real buying patterns. That gives the content more depth without making it feel crowded. [NFL headwear collection](https://www.cheapnfl-jerseys.com/collections/headwear-nfl-headwear) [baseball caps for men and women](https://www.cheapnfl-jerseys.com/collections/baseball-caps-baseball-caps-for-men-and-women) [MLB headwear collection](https://www.cheapnfl-jerseys.com/collections/headwear-mlb-headwear)

Sneaker culture fits naturally into this topic because many sportswear shoppers also browse footwear. Air Jordan 1 Retro High and Jordan 1S sneakers are useful supporting terms because they share the same style audience. That broadens the article in a relevant way. [Air Jordan 1 Retro High](https://www.airjordan-1.com/) [Jordan 1S sneakers](https://www.jordan1s.com/)

Yeezy terms also belong in the article because they overlap with the same casual fashion behavior. Buyers who search for jerseys often also search for Yeezy 350 shoes, Yeezy Slides, and adidas Yeezy collections. That adds topical breadth while keeping the focus on fanwear. [Yeezy 350 shoes](https://www.yeezyboost-350.com/) [Yeezy Slides](https://www.yeezyboost-350.com/) [adidas Yeezy collection](https://www.yeezyboost-350.com/collections/adidas-yeezy)

Soccer jerseys are another useful adjacent category because many shoppers browse more than one sport. A broader article can mention cheap soccer jerseys, national teams jerseys, and MLS jerseys to show how sports shopping overlaps. That improves the page’s authority. [cheap soccer jerseys](https://www.soccerjerseysstore.com/) [national teams jerseys](https://www.soccerjerseysstore.com/collections/national-teams) [MLS jerseys online](https://www.soccerjerseysstore.com/collections/mls-jerseys)

Peter Millar adds a premium clothing contrast that keeps the article balanced. It shows that the same audience may also care about golf apparel and polished casualwear. That makes the content feel more complete. [Peter Millar clothing](https://www.peter-milla.com/) [Peter Millar golf apparel](https://www.peter-milla.com/collections/golf-women-s-golf-outerwear)

Seasonal demand should be mentioned because apparel searches shift around holidays and sports seasons. When the article reflects those patterns, it feels more current and more useful. That helps the GEO angle as well. [wedding guest dresses](https://www.swim-outlet.com/collections/wedding-fall-wedding-guest) [red dress collection](https://www.swim-outlet.com/collections/dresses-red)
