### ISSUE TITLE
Option to render output without `data-react-helmet` attrs

### ISSUE THREAD

**Issue by namnm** [nfl/react-helmet#304] opened 2017-07-11 04:19 UTC
Thank you guys for the helmet. I have an issue that I want to render to static html files in webpack loader, and those attrs dont really help much.
Can we have an option to not to render those attrs?

**Comment by hugmanrique** [comment] 2017-08-10 20:15
Duplicate of #79

**Closed** 2017-08-11 04:01 UTC
