### ISSUE TITLE
Broken export when using Webpack 2 (React.createElement: type should not be null)

### ISSUE THREAD

**Issue by halt-hammerzeit** [nfl/react-helmet#190] opened 2016-11-05 20:46 UTC
In `3.1.0` the export is not broken: `typeof require('react-helmet') === 'function'`.
In `3.2.0` it is broken: `typeof require('react-helmet') === 'object'`.
The error is "Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components). Check the render method of `Layout`."
The cause is that `v3.2.x` of `ReactHelmet` is `{ default: function ReactHelmet() {} }` when imported in Webpack 2.

**Comment by mbifulco** [comment] 2016-11-05 21:26
Just spent an entire day with @bonitis trying to track down an issue that has this at its root.  Good find, @halt-hammerzeit!

**Comment by Bonitis** [comment] 2016-11-05 21:29
+1

**Comment by halt-hammerzeit** [comment] 2016-11-05 21:31
@mbifulco @Bonitis Yeah, this was a nontrivial one. Took me almost half an hour.

[![IMAGE ALT TEXT HERE](https://img.youtube.com/vi/76_03o9bEPQ/0.jpg)](https://www.youtube.com/watch?v=76_03o9bEPQ)

Fuck yeah, let do a circle ~~jerk~~ like

**Comment by andykenward** [comment] 2016-11-06 14:17
Looking into this issue. Not having it with `"webpack": "2.1.0-beta.22"` myself in a project. So it may be the babel setup

**Comment by halt-hammerzeit** [comment] 2016-11-06 14:27
@andykenward I'm having it with `2.1.0-beta.22`.
If it's babel setup then it's `react-helmet`'s babel transpilation setup.

**Comment by andykenward** [comment] 2016-11-06 14:42
Ah you using the `commonjs` or `es` version in your project?

https://github.com/nfl/react-helmet/blob/f0b971c467ab9854b47b5f7c808f8da464fb1ccc/package.json#L5-L7

As you need to set your babel config like this

https://github.com/andykenward/bob/blob/develop/package.json#L47-L57

**Comment by halt-hammerzeit** [comment] 2016-11-06 14:43
@andykenward Why wouldn't I use "es2015 modules"?
Isn't it the whole point of the Brave New Future where code is automatically Tree-Shaken and the bundle size is reduced and Common.js is deprectated.

**Comment by halt-hammerzeit** [comment] 2016-11-06 14:48
It works if I remove `jsnext:main` entry from `react-helmet/package.json` by the way (as you've mentioned).
But this is not a workaround since noone should tamper with 3rd party `package.json`.
My current workaround is:
https://github.com/halt-hammerzeit/react-isomorphic-render/blob/master/source/webpage%20head.js

**Comment by andykenward** [comment] 2016-11-06 14:49
@halt-hammerzeit that is why you set it to `false`. As the babel preset 2015 transform the modules to commonjs by default.

Check the docs. Under Options
https://babeljs.io/docs/plugins/preset-es2015/

> modules - Enable transformation of ES6 module syntax to another module type (Enabled by default to "commonjs").
Can be false to not transform modules, or one of ["amd", "umd", "systemjs", "commonjs"]

**Comment by halt-hammerzeit** [comment] 2016-11-06 14:56
@andykenward Well, my `babel-loader` is set up to clearly not do any transpiling of `node_modules` folder
```js
			{
				test    : /\.js$/,
				include :
				[
					path.resolve(frontend_root_folder, 'code')
				],
				loader: 'babel-loader'
			}
```

And I don't know how all this thing with Webpack and `jsnext:main` even works and there are no clues on this on the internets (the usual Webpack issue).
I suppose it kinda magically transpiles those `jsnext:main` modules by itself, possibly using Babel.
I'll ask them there:
https://github.com/webpack/webpack/issues/2902#issuecomment-241608119

**Comment by halt-hammerzeit** [comment] 2016-11-06 14:57
So, it seems like a non-`react-helmet` issue so I'm closing this, I guess

**Comment by halt-hammerzeit** [comment] 2016-11-06 15:49
@andykenward So why do you set your `"es2015"."modules"` to `false`? Do you run your code only in ES6-compatible web browsers and ignore the old browsers?

**Comment by andykenward** [comment] 2016-11-06 16:19
@halt-hammerzeit no i compile to ES5 javascript. That is why you use babel in the first place. To compile ES6/ES2015 code to ES5.

By setting the `modules` to false you stop babel from doing a transform of modules to commonjs. Which is the default behaviour for the Babel ES2015 preset.

read the doc for [`transform-es2015-modules-commonjs`](https://babeljs.io/docs/plugins/transform-es2015-modules-commonjs/)

> Babel 6 Changes
Babel 6 changed some behavior by not doing module.exports = exports['default'] anymore in the modules transforms.

>There are some caveats, but you can use babel-plugin-add-module-exports, so that updating to Babel 6 isn't a breaking change since users that don't use ES modules don't have to do require("your-module").default.

>However, it may not match how Node eventually implements ES modules natively given the the current proposal.

And if you want webpack 2 to be able to go into any npm packages that are built with support for  ES6/ES2015 version and tree shake those then you need to stop the modules transform. Otherwise you might aswell use the ES5 versions of the npm packages

There is a blog post about [Tree-shaking with webpack 2 and Babel 6](http://www.2ality.com/2015/12/webpack-tree-shaking.html). Explaining this more. But the babel setup is outdated and you can now just set `modules` to `false`. Since version [`v6.13.0`](https://github.com/babel/babel/blob/master/CHANGELOG.md#v6130-2016-08-04) of babel.

**Comment by andykenward** [comment] 2016-11-06 16:30
Oh but you may need to use the [`babel-polyfill`](https://babeljs.io/docs/usage/polyfill/) in some cases.

**Comment by halt-hammerzeit** [comment] 2016-11-06 17:32
@andykenward Well, okay, though I didn't understand a thing about all this alchemy.
But thanks for the explanations anyway.
This topic seems to be overly complicated (as all webpack-babel things are).

So, now I understand, that what `modules: false` does is it converts the module type (not the module _source_ itself, just the module _type_) into something like `commonjs`, etc.
https://babeljs.io/docs/plugins/preset-es2015/
By default it converts modules to `commonjs` which means `export default function Helmet() {}` is made into `module.exports = { default: function Helmet() {} }` which now clearly explains the source of the bug.
By turning `modules` to `false` **ALL** modules aren't converted to `commonjs` which means by fixing `react-helmet` it can potentially break all the other existing modules which worked fine before.
Or it may not.
I don't bother right now since my temporary workaround works for the time being, while the folks who're working on this topic finally make an acceptable and simple solution which works out-of-the-box without any further tweaking and hacking around.

**Comment by cwelch5** [comment] 2016-11-07 16:27
@halt-hammerzeit Apologies for the confusion with the babel setup.  We are looking into seeing how we can fix this.  Just want to be clear, you were using this library @ v3.1.0 with no problems and now with v3.2.1 your webpack build automatically picks up the `module`, which is the `es` version?

@andykenward We would prefer not to have people add special babel configuration to consume the library properly.  I thought that adding the `jsnext:main` and `module` in the package.json created a purely opt-in situation.  Will other users, besides Webpack users automatically get the `es` version?

**Comment by dlebedynskyi** [comment] 2016-11-07 16:38
@cwelch5  3.1.0 work fine. issue only for ^3.2.0. 
It would be nice to keep it as it is without special babel configs since it will be constant repeating issue

**Comment by halt-hammerzeit** [comment] 2016-11-07 16:48
@cwelch5 Yeah, I added `jsnext:main` to all my libraries because I also thought it was an opt-in feature. They seem to work by the way so I'm unsure why `jsnext:main` broke with `3.2.x` of `react-helmet`. Yes, it picks `jsnext:main` because if I erase it from `package.json` then no error happens.

**Comment by andykenward** [comment] 2016-11-07 17:49
@cwelch5 The issue is that the ES6 compiled version that is in `es` folder actually sticks to the standards for `export default`.

There are a few articles about this

[Misunderstanding ES6 Modules, Upgrading Babel, Tears, and a Solution](https://medium.com/@kentcdodds/misunderstanding-es6-modules-upgrading-babel-tears-and-a-solution-ad2d5ab93ce0#.s7gd1btag)

[ES6 Modules](https://ponyfoo.com/articles/es6#modules)

I suggest we follow how [`redux`](https://github.com/reactjs/redux/blob/5eb714c934b05b73074a3a0f156c6d2015cac93d/src/index.js#L29-L35) and [`react-router`](https://github.com/ReactTraining/react-router/blob/master/modules/index.js) do their exports without using `export default` on the entry files.

for example [redux] is (https://github.com/reactjs/redux/blob/5eb714c934b05b73074a3a0f156c6d2015cac93d/src/index.js#L29-L35)
```
export {
  createStore,
  combineReducers,
  bindActionCreators,
  applyMiddleware,
  compose
}
```
and you import in your project as

```
import {createStore} from 'redux'

So then you would have to do `import { Helmet } from 'react-helmet';`

Or i can just compile the `es` version with commonjs exports not making it `ES6`

Let me know either way and I can do a pull request in a bit.

This shouldn't effect people using the ES5 version as that

**Comment by doctyper** [comment] 2016-11-07 17:52
@andykenward That is a major change for the consumption API, which we should not do on a minor bump.

**Comment by andykenward** [comment] 2016-11-07 18:06
@doctyper perhaps it would be best to remove `module` and `jsnext:main` from

https://github.com/nfl/react-helmet/blob/master/package.json#L6-L7

Then wait for a major release to implement it

**Comment by andykenward** [comment] 2016-11-07 20:42
See pull request https://github.com/nfl/react-helmet/pull/197

**Comment by cwelch5** [comment] 2016-11-07 22:20
Apologies for the headache on this.  This is now fixed in v3.2.2

**Closed by cwelch5** 2016-11-07 22:20 UTC

**Comment by tusbar** [comment] 2017-08-28 12:17
@cwelch5 @andykenward are there any plans to revert this change and expose ES6 modules? :)

**Comment by tmbtech** [comment] 2018-11-24 22:09
https://github.com/nfl/react-helmet/pull/395/  <- uses rollup in instead of webpack to export the modules. This will allow for ESM exports.
